import logger from "../../config/logger.js";
import { RMA_STATUS, DEALER_STATUS } from "../../common/constants/status.constants.js";

const MAX_ATTACHMENTS = 6; // 5 files + 1 optional audio note, matches frontend limit
import {
  createRma as createRmaInRepo,
  createRmaAttachments,
  getRmaById as getRmaByIdFromRepo,
  getRmasByDealerId as getRmasByDealerIdFromRepo,
  getAllRmas as getAllRmasFromRepo,
  updateRmaStatus,
} from "./rma.repository.js";
import { getDealerById } from "../dealers/dealer.repository.js";

// A) createRma(dealer_id, rmaData)
// → validates dealer is ACTIVE, inserts record (rma_number generated by DB) (+ attachments)
export const createRma = async (dealer_id, rmaData) => {
  const {
    product_serial,
    product_name,
    issue_type,
    issue_description,
    purchase_date,
    warranty_status,
    warranty_expiry,
    attachments,
  } = rmaData;

  // 1. Verify dealer exists and is ACTIVE
  const dealer = await getDealerById(dealer_id);
  if (!dealer) {
    const error = new Error("Dealer not found");
    error.statusCode = 404;
    throw error;
  }
  if (dealer.status !== DEALER_STATUS.ACTIVE) {
    const error = new Error(`Cannot create RMA — dealer status is ${dealer.status}`);
    error.statusCode = 403;
    throw error;
  }

  if (attachments?.length > MAX_ATTACHMENTS) {
    const error = new Error(`Too many attachments — maximum is ${MAX_ATTACHMENTS}`);
    error.statusCode = 400;
    throw error;
  }

  // 2. Persist (rma_number is generated by the DB) and return
  const rma = await createRmaInRepo({
    dealer_id,
    product_serial,
    product_name,
    issue_type,
    issue_description,
    purchase_date,
    warranty_status,
    warranty_expiry,
  });

  if (attachments?.length) {
    rma.attachments = await createRmaAttachments(rma.id, attachments);
  }

  logger.info(`RMA created: ${rma.rma_number} for dealer ${dealer_id}`);
  return rma;
};

// B) getRmaById(id)
// → returns single RMA or throws 404
export const getRmaById = async (id) => {
  const rma = await getRmaByIdFromRepo(id);
  if (!rma) {
    const error = new Error("RMA not found");
    error.statusCode = 404;
    throw error;
  }
  return rma;
};

// C) getRmasByDealerId(dealer_id, status)
// → returns all RMAs for a dealer, optionally filtered by status
export const getRmasByDealerId = async (dealer_id, status = null) => {
  return getRmasByDealerIdFromRepo(dealer_id, status);
};

// D) getAllRmas(status)
// → admin: returns all RMAs, optionally filtered by status: PENDING | APPROVED | REJECTED
export const getAllRmas = async (status = null) => {
  return getAllRmasFromRepo(status);
};

// E) approveRma(id)
// → sets RMA status to APPROVED
export const approveRma = async (id) => {
  const rma = await updateRmaStatus(id, RMA_STATUS.APPROVED, null);
  if (!rma) {
    const error = new Error("RMA not found");
    error.statusCode = 404;
    throw error;
  }
  return rma;
};

// F) rejectRma(id, reason)
// → sets RMA status to REJECTED with a reason
export const rejectRma = async (id, reason) => {
  const rma = await updateRmaStatus(id, RMA_STATUS.REJECTED, reason);
  if (!rma) {
    const error = new Error("RMA not found");
    error.statusCode = 404;
    throw error;
  }
  return rma;
};
