import logger from "../../config/logger.js";
import { WARRANTY_STATUS } from "./rma.schema.js";
import {
  RMA_STATUS,
  DEALER_STATUS,
} from "../../common/constants/status.constants.js";

const MAX_ATTACHMENTS = 6; // 5 files + 1 optional audio note, matches frontend limit
import {
  createRma as createRmaInRepo,
  createRmaAttachments,
  getRmaById as getRmaByIdFromRepo,
  getRmaByIdOrNumber,
  getRmaAttachments,
  getRmasByDealerId as getRmasByDealerIdFromRepo,
  getRecentRmasByDealerId,
  getAllRmas as getAllRmasFromRepo,
  updateRmaStatus,
} from "./rma.repository.js";
import { getShippingEstimate } from "../../common/services/shiprocket.service.js";
import { getDealerById } from "../dealers/dealer.repository.js";
import {
  notifyRmaApproved,
  notifyRmaRejected,
} from "../notifications/notification.service.js";
import { getRepairByRmaIdOrNull } from "../repairs/repair.service.js";
import {
  getShipmentsByRmaId,
  getShipmentsByRmaIdWithHistory,
} from "../shipments/shipment.service.js";

import {
  serializeRmaDetail,
  serializeRmaSummary,
  deriveStatusLabel,
} from "./rma.serializer.js";

/////////////////////////////////////////////////////////////////////////// A) createRma(dealer_id, rmaData)
// → validates dealer is ACTIVE, inserts record (rma_number generated by DB) (+ attachments)
export const createRma = async (dealer_id, rmaData) => {
  const {
    product_serial,
    product_name,
    issue_type,
    issue_description,
    purchase_date,
    warranty_status,
    warranty_expiry,
    attachments,
    pickup_same_as_profile = true,
    pickup_address_line1,
    pickup_city,
    pickup_state,
    pickup_pincode,
  } = rmaData;

  ////////////////// 1. Verify dealer exists and is ACTIVE
  const dealer = await getDealerById(dealer_id);
  if (!dealer) {
    const error = new Error("Dealer not found");
    error.statusCode = 404;
    throw error;
  }
  if (dealer.status !== DEALER_STATUS.ACTIVE) {
    const error = new Error(
      `Cannot create RMA — dealer status is ${dealer.status}`,
    );
    error.statusCode = 403;
    throw error;
  }

  if (attachments?.length > MAX_ATTACHMENTS) {
    const error = new Error(
      `Too many attachments — maximum is ${MAX_ATTACHMENTS}`,
    );
    error.statusCode = 400;
    throw error;
  }
  ///////////////// 2. Reject out-of-warranty RMAs outright — dealer can't raise them
  if (warranty_status === WARRANTY_STATUS.OUT_OF_WARRANTY) {
    const error = new Error(
      "Out-of-warranty RMAs are not accepted — this product is not eligible for return",
    );
    error.statusCode = 400;
    throw error;
  }

  ///////////////// 3. If dealer opted for a custom pickup address, require all 4 fields
  if (!pickup_same_as_profile) {
    if (!pickup_address_line1 || !pickup_city || !pickup_state || !pickup_pincode) {
      const error = new Error(
        "pickup_address_line1, pickup_city, pickup_state and pickup_pincode are required when pickup_same_as_profile is false",
      );
      error.statusCode = 400;
      throw error;
    }
  }

  ///////////////// 4. Persist (rma_number is generated by the DB) and return
  const rma = await createRmaInRepo({
    dealer_id,
    product_serial,
    product_name,
    issue_type,
    issue_description,
    purchase_date,
    warranty_status,
    warranty_expiry,
    pickup_same_as_profile,
    pickup_address_line1: pickup_same_as_profile ? null : pickup_address_line1,
    pickup_city: pickup_same_as_profile ? null : pickup_city,
    pickup_state: pickup_same_as_profile ? null : pickup_state,
    pickup_pincode: pickup_same_as_profile ? null : pickup_pincode,
  });

  if (attachments?.length) {
    rma.attachments = await createRmaAttachments(rma.id, attachments);
  }

  logger.info(`RMA created: ${rma.rma_number} for dealer ${dealer_id}`);
  return rma;
};

// B) getRmaById(id, requesting_dealer_id)
// → returns single RMA or throws 404
// → when requesting_dealer_id is passed (dealer-facing routes), throws 403
//   if the RMA belongs to a different dealer; admin routes omit it to fetch any RMA
export const getRmaById = async (id, requesting_dealer_id = null) => {
  const rma = await getRmaByIdFromRepo(id);
  if (!rma) {
    const error = new Error("RMA not found");
    error.statusCode = 404;
    throw error;
  }
  if (requesting_dealer_id && rma.dealer_id !== requesting_dealer_id) {
    const error = new Error("Forbidden: you do not own this RMA");
    error.statusCode = 403;
    throw error;
  }
  return rma;
};

// C) getRmasByDealerId(dealer_id, status)
// → returns a dealer's RMAs as list-view summaries (frontend-facing field names + derived status)
export const getRmasByDealerId = async (dealer_id, status = null) => {
  const rmas = await getRmasByDealerIdFromRepo(dealer_id, status);
  return Promise.all(rmas.map(serializeRmaForList));
};

// D) getAllRmas(status,dealer_id)
// → admin: returns all RMAs as list-view summaries, optionally filtered by status and/or dealer_id
export const getAllRmas = async (status = null, dealer_id = null) => {
  const rmas = await getAllRmasFromRepo(status, dealer_id);
  return Promise.all(rmas.map(serializeRmaForList));
};

// Helper: assembles the repair + shipments needed to derive a summary status for one RMA
const serializeRmaForList = async (rma) => {
  const [repair, shipments] = await Promise.all([
    getRepairByRmaIdOrNull(rma.id),
    getShipmentsByRmaId(rma.id),
  ]);
  return serializeRmaSummary(rma, repair, shipments);
};

// G) getRmaDetail(identifier, requesting_dealer_id)
// → identifier may be the UUID id or the human-readable rma_number

export const getRmaDetail = async (identifier, requesting_dealer_id = null) => {
  const rma = await getRmaByIdOrNumber(identifier);
  if (!rma) {
    const error = new Error("RMA not found");
    error.statusCode = 404;
    throw error;
  }
  if (requesting_dealer_id && rma.dealer_id !== requesting_dealer_id) {
    const error = new Error("Forbidden: you do not own this RMA");
    error.statusCode = 403;
    throw error;
  }

  const [repair, shipments, attachments] = await Promise.all([
    getRepairByRmaIdOrNull(rma.id),
    getShipmentsByRmaIdWithHistory(rma.id),
    getRmaAttachments(rma.id),
  ]);

  return serializeRmaDetail(rma, { repair, shipments, attachments });
};

// H) getDashboardStats(dealer_id)
// → counts a dealer's RMAs by derived status label, for the dashboard stat cards
export const getDashboardStats = async (dealer_id) => {
  const rmas = await getRmasByDealerIdFromRepo(dealer_id);
  console.log(rmas);
  const withStatus = await Promise.all(
    rmas.map(async (rma) => {
      const [repair, shipments] = await Promise.all([
        getRepairByRmaIdOrNull(rma.id),
        getShipmentsByRmaId(rma.id),
      ]);
      return deriveStatusLabel(rma, repair, shipments);
    }),
  );

  return {
    total: withStatus.length,
    pendingApproval: withStatus.filter((s) => s === "Pending Approval").length,
    inProgress: withStatus.filter(
      (s) => s === "In Progress" || s === "Under Repair",
    ).length,
    completed: withStatus.filter((s) => s === "Completed").length,
    rejected: withStatus.filter((s) => s === "Rejected").length,
    pendingPickup: withStatus.filter(
      (s) => s === "Pending Pickup" || s === "Pickup Scheduled",
    ).length,
  };
};

// I) getRecentRmas(dealer_id, limit)
// → most recent RMAs as list-view summaries, for the dashboard's "Recent RMAs" table
export const getRecentRmas = async (dealer_id, limit = 5) => {
  const rmas = await getRecentRmasByDealerId(dealer_id, limit);
  return Promise.all(rmas.map(serializeRmaForList));
};

// E) approveRma(id)
// → sets RMA status to APPROVED — only allowed while it's still PENDING
export const approveRma = async (id) => {
  const existing = await getRmaByIdFromRepo(id);
  if (!existing) {
    const error = new Error("RMA not found");
    error.statusCode = 404;
    throw error;
  }
  if (existing.status !== RMA_STATUS.PENDING) {
    const error = new Error(
      `Cannot approve — RMA status is already ${existing.status}`,
    );
    error.statusCode = 409;
    throw error;
  }

  const rma = await updateRmaStatus(id, RMA_STATUS.APPROVED, null);
  if (!rma) {
    const error = new Error("Cannot approve — RMA status changed concurrently");
    error.statusCode = 409;
    throw error;
  }
  await notifyRmaApproved(rma);
  return rma;
};

// F) rejectRma(id, reason)
// → sets RMA status to REJECTED with a reason — only allowed while it's still PENDING
export const rejectRma = async (id, reason) => {
  const existing = await getRmaByIdFromRepo(id);
  if (!existing) {
    const error = new Error("RMA not found");
    error.statusCode = 404;
    throw error;
  }
  if (existing.status !== RMA_STATUS.PENDING) {
    const error = new Error(
      `Cannot reject — RMA status is already ${existing.status}`,
    );
    error.statusCode = 409;
    throw error;
  }

  const rma = await updateRmaStatus(id, RMA_STATUS.REJECTED, reason);
  if (!rma) {
    const error = new Error("Cannot reject — RMA status changed concurrently");
    error.statusCode = 409;
    throw error;
  }
  await notifyRmaRejected(rma);
  return rma;
};

// G)  getShippingEstimateForDealer(dealer_id)
// → looks up the dealer's pincode and asks Shiprocket for the cheapest return-shipment rate to the warehouse

export const getShippingEstimateForDealer = async (dealer_id) => {
  const dealer = await getDealerById(dealer_id);
  if (!dealer) {
    const error = new Error("Dealer not found");
    error.statusCode = 404;
    throw error;
  }

  return getShippingEstimate({
    pickupPincode: dealer.pincode,
    deliveryPincode: process.env.WAREHOUSE_PINCODE,
  });
};
